export const UPLOAD_TRAILER='UPLOAD_TRAILER'
export const UPLOAD_SLIDER='UPLOAD_SLIDER'
export const FETCH_TRAILER='FETCH_TRAILER'
export const FETCH_SLIDER='FETCH_SLIDER'
export const FETCH_LAST_SLIDER='FETCH_LAST_SLIDER'
export const FETCH_LAST_TRAILER='FETCH_LAST_TRAILER'
export const UPDATE_TRAILER='UPDATE_TRAILER'
export const UPDATE_SLIDER='UPDATE_SLIDER'
export const DELETE_TRAILER='DELETE_TRAILER'
export const DELETE_SLIDER='DELETE_SLIDER'

// trending
export const CREATE_MOVIES='CREATE_MOVIES'
export const GET_MOVIES='GET_MOVIES'
export const UPDATE_MOVIES='UPDATE_MOVIES'
export const DELETE_MOVIES='DELETE_MOVIES'
export const GET_MOVIES_BY_ID='GET_MOVIES_BY_ID'

// movies
export const CREATE_MOV='CREATE_MOV'
export const GET_MOV='GET_MOV'
export const UPDATE_MOV='UPDATE_MOV'
export const DELETE_MOV='DELETE_MOV'
export const GET_MOV_BY_ID='GET_MOV_BY_ID'
export const GET_ALL_MOV='GET_ALL_MOV'

// animated movies
export const CREATE_ANIME_MOV='CREATE_ANIME_MOV'
export const GET_ANIME_MOV='GET_ANIME_MOV'
export const UPDATE_ANIME_MOV='UPDATE_ANIME_MOV'
export const DELETE_ANIME_MOV='DELETE_ANIME_MOV'
export const GET_ANIME_MOV_BY_ID='GET_ANIME_MOV_BY_ID'
export const GET_ALL_ANIME_MOV='GET_ALL_ANIME_MOV'

// webSeries
export const CREATE_WEBSHOW='CREATE_WEBSHOW'
export const GET_WEBSHOW='GET_WEBSHOW'
export const GET_WEBSHOW_BY_ID='GET_WEBSHOW_BY_ID'
export const GET_ALL_WEBSHOW='GET_ALL_WEBSHOW'
export const UPDATE_WEBSHOW='UPDATE_WEBSHOW'
export const DELETE_WEBSHOW='DELETE_WEBSHOW'

// webSeries
export const CREATE_ANIME_SERIES='CREATE_ANIME_SERIES'
export const GET_ANIME_SERIES='GET_ANIME_SERIES'
export const GET_ANIME_SERIES_BY_ID='GET_ANIME_SERIES_BY_ID'
export const GET_ALL_ANIME_SERIES='GET_ALL_ANIME_SERIES'
export const UPDATE_ANIME_SERIES='UPDATE_ANIME_SERIES'
export const DELETE_ANIME_SERIES='DELETE_ANIME_SERIES'


// tvShow

export const CREATE_TV_SHOW='CREATE_TV_SHOW'
export const GET_TV_SHOW='GET_TV_SHOW'
export const GET_TV_SHOW_BY_ID='GET_TV_SHOW_BY_ID'
export const GET_ALL_TV_SHOW='GET_ALL_TV_SHOW'
export const UPDATE_TV_SHOW='UPDATE_TV_SHOW'
export const DELETE_TV_SHOW='DELETE_TV_SHOW'


// search

export const GET_BY_SEARCH='GET_BY_SEARCH'

// Loding state

export const START_LOADING='START_LOADING'
export const END_LOADING='END_LOADING'

// **** filter **** //

// movies 

export const FILTER_ACTION='FILTER_ACTION'
export const FILTER_ADVEN='FILTER_ADVEN'
export const FILTER_CRIME='FILTER_CRIME'
export const FILTER_ROMANCE='FILTER_ROMANCE'
export const FILTER_SCIFI='FILTER_SCIFI'
export const FILTER_THRILLER='FILTER_THRILLER'

// webSeries

export const FILTER_WEB_ACTION='FILTER_WEB_ACTION'
export const FILTER_WEB_ADVEN='FILTER_WEB_ADVEN'
export const FILTER_WEB_CRIME='FILTER_WEB_CRIME'
export const FILTER_WEB_ROMANCE='FILTER_WEB_ROMANCE'
export const FILTER_WEB_SCIFI='FILTER_WEB_SCIFI'
export const FILTER_WEB_THRILLER='FILTER_WEB_THRILLER'

// TvShow

export const FILTER_TV_ACTION='FILTER_TV_ACTION'
export const FILTER_TV_ADVEN='FILTER_TV_ADVEN'
export const FILTER_TV_CRIME='FILTER_TV_CRIME'
export const FILTER_TV_ROMANCE='FILTER_TV_ROMANCE'
export const FILTER_TV_SCIFI='FILTER_TV_SCIFI'
export const FILTER_TV_THRILLER='FILTER_TV_THRILLER'

